const images = {
    image: {
        splash: require('../../assets/images/Splash/splash.png'),
        logo: require('../../assets/images/Splash/logo.png'),
        defaultlogo: require('../../assets/images/defaultlogo.png'),
        checkbox: require('../../assets/images/unchecked.png'),
        checkboxClick: require('../../assets/images/checkboxclick.png'),
        eyeicon: require('../../assets/images/eyeicon.png'),
        disableyeicon: require('../../assets/images/eyeicondisable.png'),
        login: require('../../assets/images/login.png'),
        add: require('../../assets/images/add.png'),
        bluebell: require('../../assets/images/bluebell.png'),
        orangrbell: require('../../assets/images/orangebell.png'),
        orangeline: require('../../assets/images/orangeline.png'),
        blueline: require('../../assets/images/blueline.png'),
        liveTrackingClick: require('../../assets/images/livetrackingclick.png'),
        liveTrackingDefault: require('../../assets/images/livetrackingdefault.png'),
        usersDefault: require('../../assets/images/usersdefault.png'),
        usersClick: require('../../assets/images/userclick.png'),
        dashBoardClick: require('../../assets/images/dashboardclick.png'),
        dashBoardDefault: require('../../assets/images/dashboarddefault.png'),
        deviceAssetClick: require('../../assets/images/asste&deviceclick.png'),
        deviceAssetDefault: require('../../assets/images/asset&devicedefault.png'),
        settingDefault: require('../../assets/images/settingsdefault.png'),
        settingClick: require('../../assets/images/settingsclick.png'),
        //car: require('../../assets/images/DeviceAsset/car.png'),
        edit: require('../../assets/images/DeviceAsset/editwhite.png'),
        cardExpand: require('../../assets/images/DeviceAsset/cardExpnand.png'),
        export: require('../../assets/images/export.png'),
        list: require('../../assets/images/list.png'),
        pickupcar: require('../../assets/images/pickup-car.png'),
        puzzle: require('../../assets/images/puzzle.png'),
        usb: require('../../assets/images/usb.png'),
        user: require('../../assets/images/user.png'),
        menu: require('../../assets/images/menu.png'),
        menuclick: require('../../assets/images/menuclick.png'),
        back: require('../../assets/images/back.png'),
        down: require('../../assets/images/down.png'),
        next: require('../../assets/images/next.png'),
        add: require('../../assets/images/Manage/add.png'),
        trash: require('../../assets/images/Manage/trash.png'),
        trashBlack: require('../../assets/images/Manage/trashblack.png'),
        upArrow: require('../../assets/images/Manage/up.png'),
        downarrow: require('../../assets/images/Manage/down.png')

        
    }
}

export default images
