const images = {
    login:{
        checkedbox: require('../../assets/images/Login/checkedbox.png'),
        uncheckedbox: require('../../assets/images/Login/unchecked.png'),
    },
    manage: {
        close: require('../../assets/images/Manage/close.png'),
        closeClick: require('../../assets/images/Manage/closeClick.png'),
        editClick: require('../../assets/images/Manage/editClick.png'),
        edit: require('../../assets/images/Manage/editblack.png'),
        trash: require('../../assets/images/Manage/trash.png'),
        trashBlack: require('../../assets/images/Manage/trashblack.png')
    },
    user: {
        add: require('../../assets/images/User/add.png'),
        filter: require('../../assets/images/User/filter.png'),
        filterClick: require('../../assets/images/User/filterClick.png'),
        active: require('../../assets/images/User/active.png'),
        inactive: require('../../assets/images/User/inactive.png'),
        edit: require('../../assets/images/User/edit.png'),
        email: require('../../assets/images/User/email.png'),
        phone: require('../../assets/images/User/phone.png'),
        info: require('../../assets/images/User/info.png'),
        infoClick: require('../../assets/images/User/infoClick.png'),
        upArrow: require('../../assets/images/User/up.png'),
        downarrow: require('../../assets/images/User/down.png')
    },
    dashBoard: {
        calender: require('../../assets/images/DashBoard/calendar.png'),
        list: require('../../assets/images/DashBoard/list.png'),
        pin: require('../../assets/images/DashBoard/pin.png')
    },
    image: {
        splash: require('../../assets/images/Splash/splash.png'),
        logo: require('../../assets/images/Splash/logo.png'),
        defaultlogo: require('../../assets/images/defaultlogo.png'),
        checkbox: require('../../assets/images/unchecked.png'),        
        checkboxClick: require('../../assets/images/checkboxClick.png'),
        eyeicon: require('../../assets/images/eyeicon.png'),
        disableyeicon: require('../../assets/images/eyeicondisable.png'),
        login: require('../../assets/images/login.png'),
        add: require('../../assets/images/add.png'),
        bluebell: require('../../assets/images/bluebell.png'),
        orangrbell: require('../../assets/images/orangebell.png'),
        orangeline: require('../../assets/images/orangeline.png'),
        blueline: require('../../assets/images/blueline.png'),
        liveTrackingClick: require('../../assets/images/livetrackingclick.png'),
        liveTrackingDefault: require('../../assets/images/livetrackingdefault.png'),
        usersDefault: require('../../assets/images/usersdefault.png'),
        usersClick: require('../../assets/images/userclick.png'),
        dashBoardClick: require('../../assets/images/dashboardclick.png'),
        dashBoardDefault: require('../../assets/images/dashboarddefault.png'),
        deviceAssetClick: require('../../assets/images/asste&deviceclick.png'),
        deviceAssetDefault: require('../../assets/images/asset&devicedefault.png'),
        settingDefault: require('../../assets/images/settingsdefault.png'),
        settingClick: require('../../assets/images/settingsclick.png'),
        edit: require('../../assets/images/DeviceAsset/editwhite.png'),
        cardExpand: require('../../assets/images/DeviceAsset/cardExpnand.png'),
        export: require('../../assets/images/export.png'),
        list: require('../../assets/images/list.png'),
        pickupcar: require('../../assets/images/pickup-car.png'),
        puzzle: require('../../assets/images/puzzle.png'),
        usb: require('../../assets/images/usb.png'),
        user: require('../../assets/images/user.png'),
        menu: require('../../assets/images/menu.png'),
        menuclick: require('../../assets/images/menuclick.png'),
        back: require('../../assets/images/back.png'),
        down: require('../../assets/images/down.png'),
        next: require('../../assets/images/next.png'),
        add: require('../../assets/images/Manage/add.png'),
        trash: require('../../assets/images/Manage/trash.png'),
        trashBlack: require('../../assets/images/Manage/trashblack.png'),
        upArrow: require('../../assets/images/Manage/up.png'),
        downarrow: require('../../assets/images/Manage/down.png'),

        //settings
        settings: {
            profile: require('../../assets/images/Settings/Profile-icon.png'),
            subscription: require('../../assets/images/Settings/Subscription-icon.png'),
            paymentSettings: require('../../assets/images/Settings/PaymentSettings-icon.png'),
            permission: require('../../assets/images/Settings/Permission-icon.png'),
            about: require('../../assets/images/Settings/About-icon.png'),
            rateUs: require('../../assets/images/Settings/RateUs-icon.png'),
            feedback: require('../../assets/images/Settings/Feedback-icon.png'),
            logout: require('../../assets/images/Settings/Logout-icon.png'),
            nextArrow: require('../../assets/images/Settings/next-1.png'),
            next: require('../../assets/images/Settings/next.png'),
            email: require('../../assets/images/Settings/email.png'),
            phone: require('../../assets/images/Settings/phone.png'),
            billingAddress: require('../../assets/images/Settings/BillingAddress.png'),
            shippingAddress: require('../../assets/images/Settings/shippingAddress.png'),
            downArrow: require('../../assets/images/Settings/down-arrow.png'),
            billing: require('../../assets/images/Settings/billing.png'),
            crossIcon: require('../../assets/images/Settings/CrossIcon.png'),
            rectangle: require('../../assets/images/Settings/Rectangle.png'),
            GroupCheckBox: require('../../assets/images/Settings/GroupCheckBox.png'),
            address: require('../../assets/images/Settings/address.png'),
            editIcon: require('../../assets/images/Settings/EditIcon.png'),
            upArrow: require('../../assets/images/Settings/upArrow.png'),
            trash: require('../../assets/images/Settings/trash.png')
        }
    }
}

export default images
