require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'


target 'Gtrack' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  use_react_native!(:path => config["reactNativePath"])

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'RNLocalize', :path => '../node_modules/react-native-localize'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  # # pod 'Firebase', :modular_headers => true
  # pod 'Firebase/Core', :modular_headers => true
  # # pod 'FirebaseCoreInternal', :modular_headers => true
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  
  pod 'GoogleUtilities', :modular_headers => true
  # # $RNFirebaseAsStaticFramework = true
  # # use_flipper!()

  $FirebaseSDKVersion = '10.7.0'
  target 'GtrackTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'Gtrack-tvOS' do
  # Pods for Gtrack-tvOS

  target 'Gtrack-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
